"""Add role to User

Revision ID: c77bb3a392f3
Revises: a48366918190
Create Date: 2025-04-02 19:39:57.913631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c77bb3a392f3"
down_revision: Union[str, None] = "a48366918190"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum("user", "admin", name="user_role_enum")
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            user_role_enum,
            nullable=False,
            server_default="user",
            comment="User role: 'user', 'admin', etc.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    sa.Enum(name="user_role_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
